minor changes
railsgirls/railsgirls.github.io pull request #464
Opened 2022-03-23 16:00 UTC by snxx-lppxx

2022-03-24 04:43 UTC, hsbt commented
@snxx-lppxx Can you elaborate these changes?

2022-03-24 10:30 UTC, mmu094 approved these changes

2022-03-24 21:45 UTC, snxx-lppxx commented
Hello @hsbt, decided to reset the browser style of links upon activation... a few more changes (clarifications).

2023-01-30 20:21 UTC, tombruijn requested changes
I'm going to close this. A lot of CSS changes are unnecessary and only use more specific properties or selectors that aren't required.

2023-01-30 20:21 UTC, tombruijn commented on _layouts/default.html
> +    <main class="container">
I agree this would be better semantically, but then preferably the actual content also has an article element wrapped around it.

2023-01-30 20:21 UTC, tombruijn commented on css/style.css
> +nav a:link, nav a:active {
This `:link` addition breaks the style for when you visited the link. It looks like this for me, the not visible links have been visited.

![image](https://user-images.githubusercontent.com/282402/215586269-2bb27558-2b92-4b25-b92f-bc62613965b5.png)

2023-01-30 20:21 UTC, closed without merging